---
- name: Deploy to AWS
  hosts: web
  roles:
    - role: practical-ansible.nginx_docker
      project_name: cz-andrejovo
      project_environment: '{{ lookup("env", "PROJECT_ENVIRONMENT") }}'
      env:
        NODE_GA_CODE: '{{ lookup("env", "NODE_GA_CODE") }}'
    - role: practical-ansible.nginx-redirect
      project_name: cz-andrejovo-redirects
      server_names: www.andrejovo.cz
      destination_domain: '{{ lookup("env", "SERVER_NAME") }}'
