name: Continuous integration
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['13']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --coverage
      - name: Build app
        run: npm run build
        env:
          PACKAGE_KEY: ${{ secrets.PACKAGE_KEY }}
      - uses: trmcnvn/firefox-addon@v1
        with:
          uuid: ${{ secrets.FIREFOX_API_UUID }}
          xpi: dist/nakupuj-bez-andreje.xpi
          manifest: dist/package/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
      - uses: trmcnvn/chrome-addon@v2
        with:
          extension: ${{ secrets.CHROME_API_UUID }}
          zip: dist/nakupuj-bez-andreje.zip
          client-id: ${{ secrets.CHROME_API_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_API_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
